### ISSUE TITLE
fix/python3_dependency

### ISSUE THREAD

**Issue by Deakensbubbles** [Adjuvo/senseglove_ros_ws#14]
In some of the python scripts python 3 is used which is not normally supported by ROS melodic. When new users cleanly install a new ubuntu 18 distro with ros melodic and use our package a 'no module named rospkg' error could pop up. One script where this was already found is the finger_distance_node.py script.

**Comment by PARKBONG** [comment]
Hi @Deakensbubbles, Do you have any plan to support python3 API? I would be happy to see the API directly supported by Python as well as C.

**Comment by RPKrijnen** [comment]
Previously we have developed a C++ API which we thought would be sufficient. Maybe if there is enough interest in a Python specific API that @MaxLammers or @robinkrens can pick this up? Your question is however, not specifically related to ROS. It pertains the API which this workspace utilizes.

**Comment by robinkrens** [comment]
@PARKBONG C++ API is available here: https://github.com/Adjuvo/SenseGlove-API with some more documentation added here: https://senseglove.gitlab.io/SenseGloveDocs/native/core-api-intro.html
No plans for a python API yet. It is possible to write a simple hardware interfacing API, but you will have to implement the kinematics yourself.
