### ISSUE TITLE
Demo launch files not working with Nova Gloves

### ISSUE THREAD

**Issue by joe-louca** [Adjuvo/senseglove_ros_ws#20]
Is this package designed to work with the Nova gloves? It seems that the urdf's and controllers.yaml are not found when switching from dk1 to nova in hardware.launch.

I am trying to run senseglove_demo.launch with the Nova gloves, but receive this error:

`...
[ INFO] [1682426787.397087953]: Selected robot: dk1_left
[ INFO] [1682426787.418085831]: Selected robot: dk1_right
================================================================================REQUIRED process [senseglove/0/lh/hardware_interface-3] has died!
process has died [pid 21729, exit code -11, cmd /home/joe/senseglove_ros_ws/devel/lib/senseglove_hardware_interface/senseglove_hardware_interface_node dk1_left 0 false __name:=hardware_interface __log:=/home/joe/.ros/log/285048dc-e367-11ed-966e-95edcb31d283/senseglove-0-lh-hardware_interface-3.log].
log file: /home/joe/.ros/log/285048dc-e367-11ed-966e-95edcb31d283/senseglove-0-lh-hardware_interface-3*.log
Initiating shutdown!
================================================================================
...
`

It looks like the robot can be changed to nova_left/nova_right in hardware.launch (line 2), but this also produces errors when looking for the .urdf and .yaml files - these are present for dk1 but not nova.
`param name="robot_description" textfile="$(find senseglove_description)/urdf/$(arg robot).urdf" if="$(eval arg('is_right')==true)`
`rosparam file="$(find senseglove_hardware_interface)/config/$(arg robot)/controllers.yaml" command="load"`

Is this the route of the problem? If so, please could you add urdf and yaml files for the Nova gloves.

**Comment by akshayrmenon** [comment]
Hello, 
Apologies for the late reply. I did not receive a support ticket on this, hence I was not aware of your question. The current workspace does not have NOVA compatibility. Furthermore, there is still a discussion whether the NOVA gloves require ROS compatibility. We shall update you on this in the coming months.
