### ISSUE TITLE
Nova ROS Support

### ISSUE THREAD

**Issue by ZACHLOGAN** [Adjuvo/senseglove_ros_ws#22]
Has there been any update or change in the possibility of ROS support for the Nova gloves?

**Comment by FranBesq** [comment]
I'm also interested in this, for our project we need ROS support and we are considering developing a ROS wrapper ourselves. It would be great to know if there is a projected timeline from Adjuvo side for this feature.

For our application the features we need are:
- Read fingertip position (joint positions are no recovered right?)-> publish a joint_state publisher .
- Send haptic feedback to the nova

If we go for our own implementation:
- would you advise to extend repo or go for a wrapper of the SenseCom software. Again we just need a client to interface with the Nova. 
- Missing a urdf of the nova glove.

**Comment by akshayrmenon** [comment]
Hi @FranBesq and @ZACHLOGAN, we have scheduled our ROS 1 & 2 compatibilty of NOVA, and NOVA2. Currently as of this week, we are making the NOVA glove compatible with ROS 1 with our latest C++ Binaries. By the end of next week, after testing, we will produce a NOVA ROS Release with all the necessary updates.

**Comment by FranBesq** [comment]
@akshayrmenon are there any updates regarding the NOVA ROS1 implementation? Kindly asking :)

**Comment by akshayrmenon** [comment]
Hey @FranBesq, we are currently still in the process of refactoring. We have started only from last week, and we are pushing for a release. Based on the Management timeline, NOVA 1 Noetic Release is schedule on the 2nd week of February 2024, and then a NOVA 2 release.

I will try to update you as soon as I can.

**Comment by akshayrmenon** [comment]
![TimeLine](https://github.com/Adjuvo/senseglove_ros_ws/assets/109214172/2311289b-06ef-4c84-9cfd-9bf20456d06c)

I have shared the official Timeline of the updates. @FranBesq @ZACHLOGAN

**Comment by FranBesq** [comment]
Thanks for sharing!

**Comment by anfemosa** [comment]
@akshayrmenon, any updates on this issue? Is there a new release date?

**Comment by akshayrmenon** [comment]
Hi @anfemosa ,

As expected, we are having a few issues integrating our latest Backend v2.100.1, and latest SenseCom (communication). 

With the backend, we had linker issues as in other plugins, we use our Unreal toolchains while building the libraries, however the existing compiler, say in Ubuntu 20, cause linker issues. We have currently solved this last week. We are now currently dealing with SenseCom version issues, which we are trying to solve. On the ROS side, the code is refactored, just waiting for the backend integrations to work successfully.

**Comment by anfemosa** [comment]
Hi @akshayrmenon,
Thanks for your reply. In our lab we are looking forward to trying senseglove nova in ROS (1 or 2), we have an event in the middle of the year and we would like to have the glove in the demo, we will keep an eye out for any updates.

**Comment by akshayrmenon** [comment]
yeah, I understand. We are a small team. Currently, we are at the late stages of NOVA - 2 releases. The latest SG-Backend has major breaking changes, with the introduction of NOVA2, handlayer classes for haptics etc. The Backend Developers are currently working on Unity and Unreal SDK releases. Thought I could share some transparency in our development.

**Comment by FranBesq** [comment]
Yess, thanks for the transparency @akshayrmenon, its great to see. ofc is always hard estimating development times.
Is there an easy way of deploying the new nova-1 ROS stack with the "old" SG-Backend? From your comments I understand these new changes in SG-Backend are not relevant to the nova-1.

**Comment by akshayrmenon** [comment]
Well, currently the ROS stack is accommodated for the new backend. You can indeed use the [SenseGlove_API_v1.4.0](https://github.com/Adjuvo/SenseGlove-API) and modify the test scripts to publish topics. It is not in our scope to deploy a release with the old SG-Backend.

**Comment by akshayrmenon** [comment]
Hi @FranBesq @anfemosa I have an alpha-release branch for you guys. I will have a proper release tomorrow, with updated readme, and links to connecting the nova-glove to Linux. I have tested this with only one Nova-glove, but it should just work fine with 2 novaGloves as well, with the correct launch file parameters.

**Comment by FranBesq** [comment]
This is great, we will test it asap, thanks!

**Comment by FranBesq** [comment]
I am not able to calibrate the glove when launching the new interface, see https://github.com/Adjuvo/senseglove_ros_ws/issues/24
