### ISSUE TITLE
Calibration not working with new Nova1 ROS interface

### ISSUE THREAD

**Issue by FranBesq** [Adjuvo/senseglove_ros_ws#24]
When launching the Nova1 ROS interface with `roslaunch senseglove_launch senseglove.launch` and the glove properly connected via bluetooth the senseglove interface connects to the glove but is then stuck at the calibration phase. It is possible to continue using the interface with the glove not calibrated but this is not ideal ofc.

Normally if I launch the senseglove app manually I am able to calibrate the glove properly. Is there a way to at least store different calibration files for each person and then load them with the launcher above?

**Comment by akshayrmenon** [comment]
Hi @FranBesq, Indeed the sensecom version used is the alpha release. I can fix this quickly.

**Comment by FranBesq** [comment]
I noticed shortly after opening the issue there is a param on `senseglove.launch` for loading a calibration file. I tried using sensecom  1.3.1 to generate this calibration files (since calibration works here) but I couldnt get one. Is there a way to store such file? even if it involves using the previous version of senseglove

**Comment by akshayrmenon** [comment]
[Check out this branch](https://github.com/Adjuvo/senseglove_ros_ws/tree/fix/calibration-in-sensecom).

I have updated the sensecom version. This should work for calibration. I have not tested it with a Nova glove as I don't have one on me currently, but it should work. Do let me know if it does. If not, Let me know the output.

The calibration parameter file that you mention is specifically for one of the senseglove_finger_distance python scripts for the DK1 gloves. It shouldn't interfere with the Nova gloves.
