### ISSUE TITLE
Questions regard to glove's data and 3D visualization

### ISSUE THREAD

**Issue by tqmthong** [Adjuvo/senseglove_ros_ws#3]
Hi sense glove developers, @Deakensbubbles, we're trying to make use of the information that the glove can bring to us in our research by testing the command  `roslaunch senseglove_launch senseglove_demo.launch`.

The **first thing** we need to know about is a detailed explanation/documentation on the parameters shown when echoing `/senseglove/0/rh/joint_states` and `/senseglove/0/rh/senseglove_states` topics, which are shown in these capture:
![Screenshot from 2021-07-07 09-21-14](https://user-images.githubusercontent.com/87062711/124725977-40cded00-df05-11eb-89e1-00d6a3060145.png)
![Screenshot from 2021-07-07 09-23-15](https://user-images.githubusercontent.com/87062711/124725998-4592a100-df05-11eb-96d5-cb83be9115e7.png)

The **second thing** to be mentioned is the visualization capability of the hand on rviz. From what we've traced, the `senseglove_demo.launch` indirectly triggers `hardware.launch` later and a sequential launchers. Within `hardware.launch`, we observe the use of urdf files and various 3D virtual images of the glove's components.
![Screenshot from 2021-07-07 09-32-12](https://user-images.githubusercontent.com/87062711/124727075-47a92f80-df06-11eb-8d56-f500b3f8047e.png)
Example of one of the components that we've discovered:
![Screenshot from 2021-07-07 09-34-58](https://user-images.githubusercontent.com/87062711/124727654-d0c06680-df06-11eb-988f-ff785385d6b4.png)
However, when we try to see them on rviz, it seems not to work at all:
![Screenshot from 2021-07-07 09-40-43](https://user-images.githubusercontent.com/87062711/124728426-7ecc1080-df07-11eb-83ea-7596206500df.png)
Hence, we're wondering whether do the team have the intention for creating a 3D visualization of a glove or not and if you do, please provide us with an in-depth guide on setting it up properly.

Regards,

**Comment by LeeTaekLim** [comment]
https://github.com/LeeTaekLim/senseglove_ros_ws
Here's the visualization. Please see "visualize" branch.
