### ISSUE TITLE
Urge for a proper guide on setting up SenseGlove_API in various environments

### ISSUE THREAD

**Issue by tqmthong** [Adjuvo/senseglove_ros_ws#4]
Hi senseglove developers, we're trying to make the most of the glove in Docker Container of Ubuntu 18.04. When reading instructions on setting up SenseGlove_API library, we get confused by this contradiction given by your documentation.

Within `senseglove_ros_ws/src/SenseGlove_API/`, this promises:
![Screenshot from 2021-07-07 09-54-50](https://user-images.githubusercontent.com/87062711/124731007-be93f780-df09-11eb-9cfe-bc51c95d2510.png)
However, when we proceed to `senseglove_ros_ws/src/SenseGlove_API/Core/`, this replies:
![Screenshot from 2021-07-07 09-58-40](https://user-images.githubusercontent.com/87062711/124731284-fdc24880-df09-11eb-924c-5836b4fd1953.png)

Might I have your clarification on this and an in-depth guide on how can we make use of the library in our working environment (**Ubuntu 18.04 in a Docker Container**)?
Many thanks,

**Comment by Deakensbubbles** [comment]
Some more documentation can be found over here: [docs.senseglove.com](url) Some clarification about the contradictory statements could be provided by @MaxLammers if this is at all still a relevant issue.

**Comment by Deakensbubbles** [comment]
We have decided to adjust the READMEs mentioned before to reference the API git page. Some major changes are coming for our API and thus we will also be looking into using this new shiny version of the API in this workspace :)
