### ISSUE TITLE
About calibration and asking sample codes

### ISSUE THREAD

**Issue by LeeTaekLim** [Adjuvo/senseglove_ros_ws#5]
Dear Senseglove

Hello, we're using senseglove to control a robot hand. But the data(finger position) from the glove seems not much accurate when I checked the data using unity. So Is there any solution for improve the accuracy of the glove? And how can we calibrate the glove?

Also I think there are not much material about the glove. So it would be very thankful to you if you would give us more sample codes or some tutorials.

Thanks!

**Comment by phuicy** [comment]
Same please.

**Comment by Deakensbubbles** [comment]
Some documentation about our glove and API can be found here: [docs.senseglove.com](url) The accuracy of the finger tracking can be improved with some calibration. I have just added another issue which will tackle the implementation of a GUI to assist in calibrating the gloves #9. I'll close this issue for now as the relevant docs are now shared and the new issue should resolve the calibration issues.
