### ISSUE TITLE
Fingers inverted at joint 0

### ISSUE THREAD

**Issue by phuicy** [Adjuvo/senseglove_ros_ws#6]
I assume it is just a negative of the joint angles for joint_0 for each finger and thumb.

Fingers together: 
![image](https://user-images.githubusercontent.com/4666094/142738189-9c9ce21d-5d60-4f02-acb1-8194320fdaf0.png)

Fingers splayed:
![image](https://user-images.githubusercontent.com/4666094/142738194-91f0c6b9-c041-4685-a8de-27550c40c90d.png)

**Comment by phuicy** [comment]
By Joint0 in mean brake joint.

**Comment by Deakensbubbles** [comment]
@phuicy Although I am late with this fix, we have just set up a pull request #8 that fixes this issue. If you are up for it you can review the code before we merge. I expect the merge request to be handled within the week :)
